[package]
name = "aloepri-secret"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
aloepri-core.workspace = true
blake3.workspace = true
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true
